[package]
name = "opsctl"
version = "0.3.0"
edition = "2024"
rust-version = "1.86"
description = "CLI for the Opsd API"
homepage = "https://opsd.sh"
repository = "https://github.com/opsd-sh/opsctl"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["opsd", "cli", "operations", "business"]
categories = ["command-line-utilities"]
publish = ["crates-io"]
exclude = [".github/**", "dist-workspace.toml"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
clap_complete = "4.5"
dirs = "6.0"
hostname = "0.4.1"
opsd = "0.1.0"
reqwest = { version = "0.12.24", default-features = false, features = [
  "json",
  "rustls-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time"] }
url = { version = "2.5.7", features = ["serde"] }
webbrowser = "1.0.6"

[dev-dependencies]
tempfile = "3.23.0"

[profile.dist]
inherits = "release"
lto = "thin"
